services:
    rest-villains:
        image: quarkus/rest-villains:1.0.0-SNAPSHOT
        container_name: "rest-villains"
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "8084:8084"
        environment:
            QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/villains_database